services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=surfbnb
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data # anonymous volume to avoid persist data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
